# Generated by Django 4.1.1 on 2022-09-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='school_id',
            new_name='school',
        ),
    ]
